[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=default
style=kvantum-dark

[Fonts]
general="Noto Sans,11,-1,5,50,0,0,0,0,0"
fixed="JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
combo_animate=1
cursor_flash_time=1000
dialog_buttons_have_icons=1
font_antialias=1
font_hinting=1
gui_effects=3
itemviews_animate=1
itemviews_show_animation=1
keyboard_scheme=2
menus_have_icons=1
message_box_buttons_have_icons=1
show_shortcuts_in_context_menus=1
stylesheet=custom
tab_close_button_position=1
tool_button_style=2
toolbox_init_animation_time=150
toolbox_leave_animation_time=150
underline_shortcut=1
use_animations=1
use_hover_effects=1
wheel_scroll_lines=3

[InterfaceColors]
Background=@Variant(\0\0\0\x43\x1\xff\xff\x1a\x1a\x1a\x1a\0\0)
Base=@Variant(\0\0\0\x43\x1\xff\xff\x1e\x1e\x1e\x1e\0\0)
AlternateBase=@Variant(\0\0\0\x43\x1\xff\xff\x2a\x2a\x2a\x2a\0\0)
Button=@Variant(\0\0\0\x43\x1\xff\xff\x2a\x2a\x2a\x2a\0\0)
Text=@Variant(\0\0\0\x43\x1\xff\xff\xe6\xe6\xe6\xe6\0\0)
BrightText=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\0\0)
ButtonText=@Variant(\0\0\0\x43\x1\xff\xff\xe6\xe6\xe6\xe6\0\0)
Highlight=@Variant(\0\0\0\x43\x1\xff\xff\xd0\xd0\xd0\xff\0\0)
HighlightedText=@Variant(\0\0\0\x43\x1\xff\xff\x1a\x1a\x1a\xff\0\0)
Link=@Variant(\0\0\0\x43\x1\xff\xff\x33\xcc\xff\xff\0\0)
LinkVisited=@Variant(\0\0\0\x43\x1\xff\xff\x00\xff\x99\xff\0\0)
ToolTipBase=@Variant(\0\0\0\x43\x1\xff\xff\x3a\x3a\x3a\xff\0\0)
ToolTipText=@Variant(\0\0\0\x43\x1\xff\xff\xe6\xe6\xe6\xe6\0\0)
Window=@Variant(\0\0\0\x43\x1\xff\xff\x1a\x1a\x1a\x1a\0\0)
WindowText=@Variant(\0\0\0\x43\x1\xff\xff\xe6\xe6\xe6\xe6\0\0)

[Widgets]
draw_item_frame=0
draw_item_separator=1
draw_shadows=1
groupbox_checkable=1
groupbox_flat=0
itemviews_alternating_row_colors=0
menu_bar_always_show_separator=0
menu_bar_item_frame=1
progress_bar_chunks=0
scroll_bar_extend=0
slider_draw_notch=0
tab_bar_close_button=2
tab_bar_single_tab=0
tab_position=0