-- Generated by matugen. Do not edit; run `kome-theme apply`.
return {
    background = "rgba({{colors.background.default.hex_stripped}}ff)",
    on_background = "rgba({{colors.on_background.default.hex_stripped}}ff)",

    surface = "rgba({{colors.surface.default.hex_stripped}}ee)",
    on_surface = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
    surface_variant = "rgba({{colors.surface_variant.default.hex_stripped}}ff)",
    on_surface_variant = "rgba({{colors.on_surface_variant.default.hex_stripped}}ff)",
    surface_container = "rgba({{colors.surface_container.default.hex_stripped}}ff)",
    surface_container_high = "rgba({{colors.surface_container_high.default.hex_stripped}}ff)",
    surface_container_low = "rgba({{colors.surface_container_low.default.hex_stripped}}ff)",

    primary = "rgba({{colors.primary.default.hex_stripped}}ff)",
    on_primary = "rgba({{colors.on_primary.default.hex_stripped}}ff)",
    primary_container = "rgba({{colors.primary_container.default.hex_stripped}}ff)",
    on_primary_container = "rgba({{colors.on_primary_container.default.hex_stripped}}ff)",

    secondary = "rgba({{colors.secondary.default.hex_stripped}}ff)",
    tertiary = "rgba({{colors.tertiary.default.hex_stripped}}ff)",

    error = "rgba({{colors.error.default.hex_stripped}}ff)",
    outline = "rgba({{colors.outline.default.hex_stripped}}ff)",
    outline_variant = "rgba({{colors.outline_variant.default.hex_stripped}}ff)",

    shadow = "rgba({{colors.shadow.default.hex_stripped}}66)",
    scrim = "rgba({{colors.scrim.default.hex_stripped}}99)",

    inverse_surface = "rgba({{colors.inverse_surface.default.hex_stripped}}ff)",
    inverse_on_surface = "rgba({{colors.inverse_on_surface.default.hex_stripped}}ff)",
    inverse_primary = "rgba({{colors.inverse_primary.default.hex_stripped}}ff)",
}
