#!/usr/bin/env bash
# lint.sh — run shellcheck and basic syntax checks.

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== shellcheck ==="
if command -v shellcheck >/dev/null 2>&1; then
    shellcheck -x "$ROOT"/install.sh
    shellcheck -x "$ROOT"/install/main.sh
    shellcheck -x "$ROOT"/install/lib/*.sh
    shellcheck -x "$ROOT"/scripts/kome-*
    shellcheck -x "$ROOT"/tests/*.sh
    shellcheck -x "$ROOT"/config/quickshell/hyprquickpaper/*.sh
else
    echo "shellcheck not installed, skipping"
fi

echo ""
echo "=== bash -n ==="
bash -n "$ROOT/install.sh"
bash -n "$ROOT/install/main.sh"
for f in "$ROOT"/install/lib/*.sh; do bash -n "$f"; done
for f in "$ROOT"/scripts/kome-*; do bash -n "$f"; done
for f in "$ROOT"/tests/*.sh; do bash -n "$f"; done
for f in "$ROOT"/config/quickshell/hyprquickpaper/*.sh; do bash -n "$f"; done

echo ""
echo "=== lua syntax (luac -p) ==="
for f in "$ROOT"/config/hypr/*.lua "$ROOT"/config/hypr/modules/*.lua; do
    luac -p "$f" 2>&1 | sed "s#^#$f: #" || true
done

echo ""
echo "=== rasi (rofi theme) ==="
# rasi property/variable names cannot contain underscores; an unknown or
# illegal @name aborts the launcher with a parse-error dialog. Fail fast here.
if grep -nE '@[A-Za-z0-9-]*_' "$ROOT"/config/rofi/config.rasi; then
    echo "error: underscore in @reference in config/rofi/config.rasi (illegal in rasi)" >&2
    exit 1
fi
# every @reference in config.rasi must resolve: either a local alias from its
# own top-level block or a color generated by the matugen template.
python3 - "$ROOT" <<'EOF'
import re, sys
root = sys.argv[1]
rasi = open(f"{root}/config/rofi/config.rasi").read()
tpl = open(f"{root}/config/matugen/templates/rofi-colors.rasi").read()
used = set(re.findall(r'@([A-Za-z0-9-]+)', rasi)) - {'import'}
defined = set(re.findall(r'^\s*([a-z][a-z0-9-]*)\s*:', tpl + rasi, re.M))
missing = sorted(u for u in used if u not in defined)
if missing:
    print(f"error: unresolvable @references in config.rasi: {missing}", file=sys.stderr)
    sys.exit(1)
print(f"rasi refs ok ({len(used)} references resolve)")
EOF

echo ""
echo "=== lint complete ==="