#!/usr/bin/env bash
# kome installer — provider registry.
#
# Every swappable component has a default provider and a list of alternatives.
# The installer installs only the selected provider's packages and symlinks
# only its config. Runtime scripts read ~/.config/kome/providers.env.
#
# To add a provider: append it to providers_for(), then add its packages to
# provider_packages() and (if it ships config) provider_configs().
# Sourced by install/main.sh and by kome-session.

# Order matters: the default is first.
KOME_COMPONENTS=(bar lock idle wallpaper notifications launcher osd screenshot clipboard filemanager)

kome_component_label() {
    case "$1" in
        bar)           echo "status bar" ;;
        lock)          echo "lock screen" ;;
        idle)          echo "idle daemon" ;;
        wallpaper)     echo "wallpaper daemon" ;;
        notifications) echo "notification daemon" ;;
        launcher)      echo "application launcher" ;;
        osd)           echo "on-screen display" ;;
        screenshot)    echo "screenshot tool" ;;
        clipboard)     echo "clipboard history" ;;
        filemanager)   echo "file manager" ;;
        *)             echo "$1" ;;
    esac
}

providers_for() {
    case "$1" in
        bar)           echo "waybar quickshell" ;;
        lock)          echo "hyprlock swaylock wlogout" ;;
        idle)          echo "hypridle swayidle" ;;
        wallpaper)     echo "hyprpaper awww quickshell" ;;
        notifications) echo "swaync mako dunst" ;;
        launcher)      echo "rofi wofi fuzzel" ;;
        osd)           echo "swayosd quickshell none" ;;
        screenshot)    echo "grim hyprshot" ;;
        clipboard)     echo "cliphist none" ;;
        filemanager)   echo "yazi thunar" ;;
    esac
}

provider_default() { providers_for "$1" | awk '{print $1}'; }

# Official-repo packages for a provider.
provider_packages() {
    case "$1:$2" in
        bar:waybar)            echo "waybar" ;;
        bar:quickshell)        echo "quickshell" ;;
        lock:hyprlock)         echo "hyprlock" ;;
        lock:swaylock)         echo "swaylock" ;;
        lock:wlogout)          echo "wlogout" ;;
        idle:hypridle)         echo "hypridle" ;;
        idle:swayidle)         echo "swayidle" ;;
        wallpaper:hyprpaper)   echo "hyprpaper" ;;
        wallpaper:awww)        echo "awww" ;;
        wallpaper:quickshell)  echo "quickshell" ;;
        notifications:swaync)  echo "swaync" ;;
        notifications:mako)    echo "mako" ;;
        notifications:dunst)   echo "dunst" ;;
        launcher:rofi)         echo "rofi" ;;
        launcher:wofi)         echo "wofi" ;;
        launcher:fuzzel)       echo "fuzzel" ;;
        osd:swayosd)           echo "swayosd" ;;
        osd:quickshell)        echo "quickshell" ;;
        osd:none)              echo "" ;;
        screenshot:grim)       echo "grim slurp" ;;
        screenshot:hyprshot)   echo "hyprshot" ;;
        clipboard:cliphist)    echo "cliphist wl-clipboard" ;;
        clipboard:none)        echo "wl-clipboard" ;;
        filemanager:yazi)      echo "yazi" ;;
        filemanager:thunar)    echo "thunar" ;;
        *)                     echo "" ;;
    esac
}

# AUR packages for a provider (empty when none needed).
provider_aur_packages() {
    case "$1:$2" in
        lock:wlogout)      echo "wlogout" ;;
        bar:quickshell)    echo "" ;;
        *)                 echo "" ;;
    esac
}

# Config directories under config/ that must be symlinked for this provider.
# Hypr-ecosystem files (hyprlock/hypridle/hyprpaper) live inside config/hypr and
# are always present; only standalone config dirs are listed here.
provider_configs() {
    case "$1:$2" in
        bar:waybar)              echo "waybar" ;;
        bar:quickshell)          echo "quickshell" ;;
        notifications:swaync)    echo "swaync" ;;
        notifications:mako)      echo "mako" ;;
        notifications:dunst)     echo "dunst" ;;
        launcher:rofi)           echo "rofi" ;;
        launcher:wofi)           echo "wofi" ;;
        launcher:fuzzel)         echo "fuzzel" ;;
        filemanager:yazi)        echo "yazi" ;;
        *)                       echo "" ;;
    esac
}

# Write providers.env from the KOME_SELECTED_* variables set by the installer.
write_providers_file() {
    local component var value
    run mkdir -p "$KOME_STATE_DIR"
    if [[ "$DRY_RUN" == "1" ]]; then
        printf '%s\n' "${C_DIM}[dry-run]${C_RESET} write $KOME_PROVIDERS_FILE"
        return 0
    fi
    : >"$KOME_PROVIDERS_FILE"
    {
        echo "# Generated by kome installer $(date -Iseconds). Edit to swap components."
        for component in "${KOME_COMPONENTS[@]}"; do
            var="KOME_$(printf '%s' "$component" | tr '[:lower:]' '[:upper:]')"
            value="${!var}"
            printf '%s=%s\n' "$var" "$value"
        done
        printf 'KOME_PROFILE=%s\n' "$KOME_PROFILE"
        printf 'KOME_SHELL=%s\n' "$KOME_SHELL_CHOICE"
    } >>"$KOME_PROVIDERS_FILE"
}
